version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 81:80
    volumes:
      - wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 123456789
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: wp.mydessk.com
      LETSENCRYPT_HOST: wp.mydessk.com
      LETSENCRYPT_EMAIL: info@mydessk.com
    networks:
      - seshub
      - default

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 123456789
      MYSQL_RANDOM_ROOT_PASSWORD: '0'
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - default
  adminer:
    image: adminer
    restart: always
    ports:
      - 3001:8080




volumes:
  db:
  wordpress:

networks:
  seshub:
    external: true
  default:
    driver: bridge

