version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    volumes:
      - wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./cvs:/var/www/html/cvs
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 123456789
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: wp-test.mydessk.com
      LETSENCRYPT_HOST: wp-test.mydessk.com
      LETSENCRYPT_EMAIL: info@mydessk.com
      WP_DEBUG: 1
    networks:
      - seshub
      - default

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_PASSWORD: 123456789
    volumes:
      - db:/var/lib/mysql
    networks:
      - default
  adminer:
    image: adminer
    restart: always
    ports:
      - 3001:8080

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/app/app/static/
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    depends_on:
      - app
  letsencrypt:
    restart: always
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy



volumes:
  html:
  certs:
  vhost:
  static:
  wordpress:
  db:



networks:
  default:
    driver: bridge

